apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kv-provider
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"   # We will not use pod identity for this example. We will use SP
    keyvaultName: "key vault name"   # This is the name of KeyVault resource that we created in previous step
    cloudName: "AzurePublicCloud"
    objects:  |
      array:
        - |
          objectName: db-username
          objectType: secret      # object types: secret, key or cert
          objectVersion: "secret version "
        - |
          objectName: db-password
          objectType: secret   
          objectVersion: "secret version"
        - |
          objectName: dbrootpassword
          objectType: secret   
          objectVersion: "secret version"
        - |
          objectName: dbname
          objectType: secret   
          objectVersion: "secret version"     
      
    resourceGroup: "key vault resource group name"    # Resource goup that you have used to create KeyVault
    subscriptionId: "subscription id"       
    tenantId: "tenant id"           
  secretObjects:                             
  - secretName: db-secret  
    data:
    - key: dbuser                         
      objectName: db-username   
    - key: dbpassword                          
      objectName: db-password 
    - key: dbrootpassword                          
      objectName: dbrootpassword 
    - key: dbname                          
      objectName: dbname                                      
    type: Opaque