apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "wikimedia.fullname" . }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ template "wikimedia.fullname" . }}-web
            port:
              number: 80